FROM node:18-alpine
WORKDIR /app
RUN npm install pm2 -g
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx vite build
EXPOSE 8080
CMD ["pm2-runtime", "start", "npx", "--name", "allstarteams-app", "--", "tsx", "server/index.ts"]
