-- Allow AI-generated image types in photo_storage.image_type
-- ==========================================================
-- server/services/photo-storage-service.ts writes 'dalle_stretch',
-- 'dalle_ridiculous' and 'dalle_capability' (ImageType enum), but the original
-- chk_image_type_valid constraint only permitted the five pre-existing types.
-- Every AI image insert therefore violated the constraint, storePhoto() threw,
-- and image-gen fell back to returning a ~2.3MB base64 data URL inline
-- (`storage_fallback: true`) instead of a stored photo id.
--
-- Dev had already been widened by hand, which is why it worked there and not in
-- production -- the change was never captured as a migration. This commits it.
--
-- Note: the 'dalle_' prefix is historical. Images are generated by gpt-image-1
-- (dall-e-3 is retired on this account); these are opaque type labels, not a
-- model reference. Renaming them is a separate change -- it would require
-- migrating existing rows in dev and updating the enum in code.

ALTER TABLE photo_storage DROP CONSTRAINT IF EXISTS chk_image_type_valid;

ALTER TABLE photo_storage ADD CONSTRAINT chk_image_type_valid
  CHECK (image_type IN (
    'profile_picture',
    'starcard_generated',
    'workshop_visualization',
    'workshop_upload',
    'general_upload',
    'dalle_stretch',
    'dalle_ridiculous',
    'dalle_capability'
  ));
